#!/usr/bin/env bash

set -e

# #### Ehi...
# Se stai usando VS Code, invece di usare questo script ti
# suggerisco di avviare il debugger direttamente. C'è una voce
# funzionante di debugpy in launch.json (basta premere F5).


cd "$(dirname "$0")/.."

if [[ ! -f "$VENV/bin/activate" ]]; then
    echo "ERRORE: Nessun venv trovato, assicurati di eseguire prima il setup!"
    exit 1
fi

source $VENV/bin/activate


# Crea la cartella config se non è presente
if [[ ! -d "${PWD}/config" ]]; then
    mkdir -p "${PWD}/config"
    hass --config "${PWD}/config" --script ensure_config
fi

# Imposta il percorso per i custom_components
## Questo ci permette di avere la struttura <root>/custom_components/ble_radar
## e contemporaneamente la configurazione di Home Assistant dentro <root>/config
## senza ricorrere a symlink.
#
# Nota: questo metodo funzionava con il debugger integrato di Python (deprecato).
# Per il nuovo debugger debugpy, è meglio usare direttamente F5 in VS Code.
export PYTHONPATH="${PYTHONPATH}:${PWD}/custom_components"

# Avvia Home Assistant
hass --config "${PWD}/config" --debug
